apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ausf-config
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |
    logger:
        file: /var/log/ausf.log
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
    ausf:
      sbi:
      - addr: 0.0.0.0
        advertise: {{ .Release.Name }}-ausf
    nrf:
     sbi:
      name: {{ .Release.Name }}-nrf