apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-bsf-config
  labels:
    epc-mode: bsf
data:
  bsf.yaml: |
    logger:
        file: /var/log/bsf.log
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
    bsf:
      sbi:
      - addr: 0.0.0.0
        advertise: {{ .Release.Name }}-bsf
    nrf:
     sbi:
      name: {{ .Release.Name }}-nrf