apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nrf-config
  labels:
    epc-mode: nrf
data:
  nrf.yaml: |
    logger:
        file: /var/log/nrf.log
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
    nrf:
        sbi:
          addr: 0.0.0.0
