apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nssf
  labels:
    epc-mode: nssf
spec:
  selector:
    epc-mode: nssf
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80  
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nssf-deployment  
  labels:
    epc-mode: nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nssf
  template:
    metadata:
      labels:
        epc-mode: nssf
    spec:
      serviceAccountName: {{ .Release.Name }}-k8s-wait-for
      initContainers:     
      - name: wait-for-nrf
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lepc-mode=nrf"      
      containers:
        - name: nssf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-nssfd", "-c", "/open5gs/configs/open5gs/nssf.yaml"]
          volumeMounts:
          - name: {{ .Release.Name }}-nssf-config
            mountPath: /open5gs/configs/open5gs/nssf.yaml
            subPath: "nssf.yaml"    
      volumes:
        - name: {{ .Release.Name }}-nssf-config
          configMap:
            name: {{ .Release.Name }}-nssf-config           
