apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nssf-config
  labels:
    epc-mode: nssf
data:
  nssf.yaml: |
    logger:
        file: /var/log/nssf.log   
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
    nssf:
      sbi:     
      - addr: 0.0.0.0
        advertise: {{ .Release.Name }}-nssf
      nsi:
      - addr: {{ .Release.Name }}-nrf
        port: 80
        s_nssai:
          sst: {{ .Values.nssf.sst }}
    nrf:
     sbi:
      name: {{ .Release.Name }}-nrf