apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-smf
  labels:
    epc-mode: smf
spec:
  selector:
    epc-mode: smf
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80  
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-smf-deployment
  labels:
    epc-mode: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: smf
  template:
    metadata:
      annotations:
      labels:
        epc-mode: smf
        epc-prom: enabled
    spec:             
      containers:
      - name: smf
        image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
        imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
        ports:
        - containerPort: 9090
          name: prom
          protocol: TCP       
        command: ["/bin/sh", "-c"]
        args:
        - apt-get update;
          apt-get install iputils-ping iperf3 -y;
          open5gs-smfd -c /open5gs/configs/open5gs/smf.yaml;
        volumeMounts:
          - name: {{ .Release.Name }}-smf-config
            mountPath: /open5gs/configs/open5gs/smf.yaml
            subPath: "smf.yaml"          
        securityContext:
           capabilities:
             add:
             - NET_ADMIN 
      volumes:
        - name: {{ .Release.Name }}-smf-config
          configMap:
            name: {{ .Release.Name }}-smf-config                
