apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-smf-config
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
        file: /var/log/smf.log

    parameter:
        no_ipv6: true
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
    smf:
        sbi:     
        - addr: 0.0.0.0
          advertise: {{ .Release.Name }}-smf
        pfcp:
           dev: {{ .Values.smf.N4Int }}
        gtpc:
           dev: {{ .Values.smf.N4Int }}
        gtpu:
           dev: {{ .Values.smf.N4Int }}
        subnet:
         - addr: 10.45.0.1/16
           dnn: {{ .Values.dnn }}
        dns:
          - 8.8.8.8
          - 8.8.4.4
        mtu: 1400

    nrf:
     sbi:
      name: {{ .Release.Name }}-nrf 

    upf:
      pfcp:
        - addr: upf.open5gs.service
          dnn: {{ .Values.dnn }}
