apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: core5g-def
  namespace: open5gs
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "host-device",
      "master": "eth1",
      "mode": "l2",
      "ipam": {
        "type": "host-local",
        "subnet": "100.0.50.0/24",
        "rangeStart": "100.0.50.10",
        "rangeEnd": "100.0.50.30",
        "gateway": "100.0.50.9"
      }
    }'