# This contains the original code for 5gcore-sctp-loadbalancer.
# Licensed under the Apache License, Version 2.0.
# You can find the original code at https://github.com/infinitydon/5gcore-sctp-loadbalancer/blob/main/open5gs-helm-charts/values.yaml

# Default values for open5gs-epc-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

open5gs:
  image:
    repository: 542548491317.dkr.ecr.us-west-2.amazonaws.com/ecr-cdk-stack-myopen5gs41a0c7ec-by5aqtmexdsx
    pullPolicy: IfNotPresent
    tag: "v265"

webui:
  image:
    repository: 542548491317.dkr.ecr.us-east-2.amazonaws.com/open5gs-x86-web
    pullPolicy: IfNotPresent
    tag: "41fd851"

ueImport:
  image:
    repository: free5gmano/nextepc-mongodb
    pullPolicy: IfNotPresent
    tag: "latest"

simulator:  
   ue1:
     imsi: "208930000000031"
     op: "63bfa50ee6523365ff14c1f45f88737d"
     secKey: "0C0A34601D4F07677303652C0462535B"
     sst: "1"
     sd: "1"
   ue2:
     imsi: "208930000000032"
     imei: "356938035643803"
     imeiSv: "4370816125816151"
     op: "63bfa50ee6523365ff14c1f45f88737d"
     secKey: "0C0A34601D4F07677303652C0462535B"
     sst: "1"
     sd: "1"     

dnn: internet

k8swait:
  repository: groundnuty/k8s-wait-for
  tag: v1.6
  pullPolicy: IfNotPresent  

k8s:
  interface: eth0

amf1:
  mcc: 208
  mnc: 93
  tac: 7
  networkName: Open5GS
  ngapInt: eth0

smf:
  N4Int: eth0

upf:
  N3N4Int: eth0

nssf:
  sst: "1"
  sd: "1"  

prometheus:
  nodeExporter:
     repository: quay.io/prometheus/node-exporter
     tag: v1.3.1
     pullPolicy: IfNotPresent